import React from 'react';
export const category = [
  {text: 'همه'},
  {text: 'سنگک'},
  {text: 'بربری'},
  {text: 'سنتی'},
  {text: 'فانتزی'},
  {text: 'بربری'},
  {text: 'همه'},
  {text: 'سنگک'},
  {text: 'بربری'},
  {text: 'سنتی'},
  {text: 'فانتزی'},
  {text: 'بربری'},
];
export const topBread = [
  {
    name: 'بربری خاشخاشی ۴۵۰ گرم',
    imageSrc: require('../assets/testImg/barbari_circle.png'),
    price: 1750,
    prevPrice: 2500,
    discountPercent: 7,
  },
  {
    name: 'سنگک سنتی ۷۵۰ گرم',
    imageSrc: require('../assets/testImg/sangak.png'),
    price: 1500,
    prevPrice: 2000,
    discountPercent: 5,
  },
  {
    name: 'سنگک سنتی ۷۵۰ گرم',
    imageSrc: require('../assets/testImg/sangak.png'),
    price: 1500,
    prevPrice: 2000,
    discountPercent: 5,
  },
  {
    name: 'سنگک سنتی ۷۵۰ گرم',
    imageSrc: require('../assets/testImg/sangak.png'),
    price: 1500,
    prevPrice: 2000,
    discountPercent: 5,
  },
];
export const addressList = [
  {
    id: 1,
    province: 'اصفهان',
    city: 'کاشان',
    address: ' میدان امام حسین, کوی اندیشه, پلاک ۶۷',
    phone: '۰۳۱۵۵۴۵۳۴۲۳',
  },
  {
    id: 2,
    province: 'کرمان',
    city: 'کاشان',
    address: ' میدان امام حسین, کوی اندیشه, پلاک ۶۷',
    phone: '۰۳۱۵۵۴۵۳۴۲۳',
  },
  {
    id: 3,
    province: 'تهران',
    city: 'کاشان',
    address: ' میدان امام حسین, کوی اندیشه, پلاک ۶۷',
    phone: '۰۳۱۵۵۴۵۳۴۲۳',
  },
  {
    id: 4,
    province: 'بندرعباس',
    city: 'کاشان',
    address: ' میدان امام حسین, کوی اندیشه, پلاک ۶۷',
    phone: '۰۳۱۵۵۴۵۳۴۲۳',
  },
  {
    id: 5,
    province: 'بوشهر',
    city: 'کاشان',
    address: ' میدان امام حسین, کوی اندیشه, پلاک ۶۷',
    phone: '۰۳۱۵۵۴۵۳۴۲۳',
  },
  // {
  //   id: 6,
  //   province: 'اصفهان',
  //   city: 'کاشان',
  //   address: ' میدان امام حسین, کوی اندیشه, پلاک ۶۷',
  //   phone: '۰۳۱۵۵۴۵۳۴۲۳',
  // },
  // {
  //   id: 7,
  //   province: 'اصفهان',
  //   city: 'کاشان',
  //   address: ' میدان امام حسین, کوی اندیشه, پلاک ۶۷',
  //   phone: '۰۳۱۵۵۴۵۳۴۲۳',
  // },
];

export const bread = [
  {
    id: 1,
    name: 'تافتون تنوری ۵۰۰ گرم',
    imageSrc: require('../assets/testImg/taftoon.png'),
    price: 1500,
    prevPrice: 2000,
    discountPercent: 5,
    count: 2,
  },
  {
    id: 2,
    name: 'بربری ساده ۴۵۰ گرم',
    imageSrc: require('../assets/testImg/barbari.png'),
    price: 1750,
    prevPrice: 2500,
    discountPercent: 7,
    count: 4,
  },
  {
    id: 3,
    name: 'سنگک سنتی ۷۵۰ گرم',
    imageSrc: require('../assets/testImg/sangak.png'),
    price: 1500,
    prevPrice: 2000,
    discountPercent: 5,
    count: 7,
  },
  {
    id: 4,
    name: 'بربری خاشخاشی ۴۵۰ گرم',
    imageSrc: require('../assets/testImg/barbari_circle.png'),
    price: 1750,
    prevPrice: 2500,
    discountPercent: 7,
    count: 6,
  },
];

export const swiper = [
  {imageSrc: require('../assets/testImg/barbari_circle.png')},
  {imageSrc: require('../assets/testImg/barbari_circle.png')},
];

export const questionAnswer = [
  {
    question: 'چگونه سفارش بدهیم',
    answer:
      'در صفحه نخست با کلیک بر روی هر نان  ورفتن به صفحه جزییات ان میتوانید نان را به سبد خرید خود اضافه کرده سپس  به سبد خرید رفته و سفارش خود را با چرداخت وجه نهایی کنید ',
  },
  {
    question: 'امکان پرداخت وجه در درب منزل وجود دارد',
    answer: 'بله وجو دارد هنگام خرید گزینه پرداخت حضوری را انتخاب کنید',
  },
  {
    question: 'چگونه به اپلیکیشن شما اعتماد کنیم؟',
    answer:
      'دارا بودن نماد اعتماد الکترونیک به هر کسب و کار و اپلیکیشن رسمیت و اعتبار می بخشد',
  },
  {
    question:
      'اگر در هنگام خرید دوبار پرداخت کردیم چگونه وجه خود را پس بگیریم  ',
    answer: 'با واحد پشتیبانی تماس بگیرید ',
  },
];

export const cities = [
  [
    {id: 61, title: 'آبش احمد', state_id: 1},
    {id: 52, title: 'آذرشهر', state_id: 1},
    {id: 35, title: 'آقکند', state_id: 1},
    {id: 46, title: 'اچاچی', state_id: 1},
    {id: 39, title: 'اسکو', state_id: 1},
    {id: 33, title: 'اهر', state_id: 1},
    {id: 14, title: 'ایلخچی', state_id: 1},
    {id: 19, title: 'باسمنج', state_id: 1},
    {id: 34, title: 'بخشایش', state_id: 1},
    {id: 43, title: 'بستان آباد', state_id: 1},
    {id: 56, title: 'بناب', state_id: 1},
    {id: 24, title: 'بناب مرند', state_id: 1},
    {id: 44, title: 'تبریز', state_id: 1},
    {id: 59, title: 'ترک', state_id: 1},
    {id: 10, title: 'ترکمانچای', state_id: 1},
    {id: 12, title: 'تسوج', state_id: 1},
    {id: 18, title: 'تیکمه داش', state_id: 1},
    {id: 4, title: 'تیمورلو', state_id: 1},
    {id: 45, title: 'جلفا', state_id: 1},
    {id: 36, title: 'جوان قلعه', state_id: 1},
    {id: 49, title: 'خاروانا', state_id: 1},
    {id: 29, title: 'خامنه', state_id: 1},
    {id: 51, title: 'خداجو', state_id: 1},
    {id: 30, title: 'خسروشاه', state_id: 1},
    {id: 22, title: 'خمارلو', state_id: 1},
    {id: 23, title: 'خواجه', state_id: 1},
    {id: 3, title: 'دوزدوزان', state_id: 1},
    {id: 9, title: 'زرنق', state_id: 1},
    {id: 13, title: 'زنوز', state_id: 1},
    {id: 54, title: 'سراب', state_id: 1},
    {id: 6, title: 'سردرود', state_id: 1},
    {id: 1, title: 'سهند', state_id: 1},
    {id: 2, title: 'سیس', state_id: 1},
    {id: 20, title: 'سیه رود', state_id: 1},
    {id: 53, title: 'شبستر', state_id: 1},
    {id: 41, title: 'شربیان', state_id: 1},
    {id: 15, title: 'شرفخانه', state_id: 1},
    {id: 40, title: 'شندآباد', state_id: 1},
    {id: 5, title: 'صوفیان', state_id: 1},
    {id: 60, title: 'عجب شیر', state_id: 1},
    {id: 25, title: 'قره آغاج', state_id: 1},
    {id: 58, title: 'کلوانق', state_id: 1},
    {id: 37, title: 'کلیبر', state_id: 1},
    {id: 50, title: 'کوزه کنان', state_id: 1},
    {id: 42, title: 'گوگان', state_id: 1},
    {id: 31, title: 'لیلان', state_id: 1},
    {id: 17, title: 'مبارک شهر', state_id: 1},
    {id: 27, title: 'مراغه', state_id: 1},
    {id: 38, title: 'مرند', state_id: 1},
    {id: 55, title: 'ملکان', state_id: 1},
    {id: 28, title: 'ممقان', state_id: 1},
    {id: 16, title: 'مهربان', state_id: 1},
    {id: 21, title: 'میانه', state_id: 1},
    {id: 32, title: 'نظرکهریزی', state_id: 1},
    {id: 7, title: 'هادیشهر', state_id: 1},
    {id: 47, title: 'هریس', state_id: 1},
    {id: 8, title: 'هشترود', state_id: 1},
    {id: 57, title: 'هوراند', state_id: 1},
    {id: 26, title: 'وایقان', state_id: 1},
    {id: 11, title: 'ورزقان', state_id: 1},
    {id: 48, title: 'یامچی', state_id: 1},
  ],
  [
    {id: 79, title: 'آواجیق', state_id: 2},
    {id: 101, title: 'ارومیه', state_id: 2},
    {id: 88, title: 'اشنویه', state_id: 2},
    {id: 64, title: 'ایواوغلی', state_id: 2},
    {id: 67, title: 'باروق', state_id: 2},
    {id: 69, title: 'بازرگان', state_id: 2},
    {id: 90, title: 'بوکان', state_id: 2},
    {id: 86, title: 'پلدشت', state_id: 2},
    {id: 91, title: 'پیرانشهر', state_id: 2},
    {id: 62, title: 'تازه شهر', state_id: 2},
    {id: 72, title: 'تکاب', state_id: 2},
    {id: 92, title: 'چهاربرج', state_id: 2},
    {id: 85, title: 'خلیفان', state_id: 2},
    {id: 82, title: 'خوی', state_id: 2},
    {id: 73, title: 'دیزج دیز', state_id: 2},
    {id: 71, title: 'ربط', state_id: 2},
    {id: 89, title: 'زرآباد', state_id: 2},
    {id: 97, title: 'سردشت', state_id: 2},
    {id: 84, title: 'سرو', state_id: 2},
    {id: 78, title: 'سلماس', state_id: 2},
    {id: 68, title: 'سیلوانه', state_id: 2},
    {id: 74, title: 'سیمینه', state_id: 2},
    {id: 96, title: 'سیه چشمه', state_id: 2},
    {id: 65, title: 'شاهین دژ', state_id: 2},
    {id: 94, title: 'شوط', state_id: 2},
    {id: 99, title: 'فیرورق', state_id: 2},
    {id: 103, title: 'قره ضیاءالدین', state_id: 2},
    {id: 80, title: 'قطور', state_id: 2},
    {id: 93, title: 'قوشچی', state_id: 2},
    {id: 98, title: 'کشاورز', state_id: 2},
    {id: 66, title: 'گردکشانه', state_id: 2},
    {id: 95, title: 'ماکو', state_id: 2},
    {id: 100, title: 'محمدیار', state_id: 2},
    {id: 81, title: 'محمودآباد', state_id: 2},
    {id: 77, title: 'مرگنلر', state_id: 2},
    {id: 102, title: 'مهاباد', state_id: 2},
    {id: 76, title: 'میاندوآب', state_id: 2},
    {id: 87, title: 'میرآباد', state_id: 2},
    {id: 70, title: 'نازک علیا', state_id: 2},
    {id: 63, title: 'نالوس', state_id: 2},
    {id: 83, title: 'نقده', state_id: 2},
    {id: 75, title: 'نوشین', state_id: 2},
  ],
  [
    {id: 129, title: 'آبی بیگلو', state_id: 3},
    {id: 108, title: 'اردبیل', state_id: 3},
    {id: 109, title: 'اسلام اباد', state_id: 3},
    {id: 114, title: 'اصلاندوز', state_id: 3},
    {id: 128, title: 'بیله سوار', state_id: 3},
    {id: 104, title: 'پارس آباد', state_id: 3},
    {id: 124, title: 'تازه کند', state_id: 3},
    {id: 110, title: 'تازه کندانگوت', state_id: 3},
    {id: 112, title: 'جعفرآباد', state_id: 3},
    {id: 116, title: 'خلخال', state_id: 3},
    {id: 126, title: 'رضی', state_id: 3},
    {id: 127, title: 'سرعین', state_id: 3},
    {id: 123, title: 'عنبران', state_id: 3},
    {id: 105, title: 'فخراباد', state_id: 3},
    {id: 125, title: 'قصابه', state_id: 3},
    {id: 106, title: 'کلور', state_id: 3},
    {id: 117, title: 'کوراییم', state_id: 3},
    {id: 120, title: 'گرمی', state_id: 3},
    {id: 119, title: 'گیوی', state_id: 3},
    {id: 121, title: 'لاهرود', state_id: 3},
    {id: 115, title: 'مرادلو', state_id: 3},
    {id: 111, title: 'مشگین شهر', state_id: 3},
    {id: 113, title: 'نمین', state_id: 3},
    {id: 107, title: 'نیر', state_id: 3},
    {id: 122, title: 'هشتجین', state_id: 3},
    {id: 118, title: 'هیر', state_id: 3},
  ],
  [
    {id: 185, title: 'آران وبیدگل', state_id: 4},
    {id: 236, title: 'ابریشم', state_id: 4},
    {id: 143, title: 'ابوزیدآباد', state_id: 4},
    {id: 164, title: 'اردستان', state_id: 4},
    {id: 191, title: 'اژیه', state_id: 4},
    {id: 144, title: 'اصغرآباد', state_id: 4},
    {id: 220, title: 'اصفهان', state_id: 4},
    {id: 208, title: 'افوس', state_id: 4},
    {id: 169, title: 'انارک', state_id: 4},
    {id: 171, title: 'ایمانشهر', state_id: 4},
    {id: 200, title: 'بادرود', state_id: 4},
    {id: 221, title: 'باغ بهادران', state_id: 4},
    {id: 234, title: 'باغشاد', state_id: 4},
    {id: 145, title: 'بافران', state_id: 4},
    {id: 160, title: 'برزک', state_id: 4},
    {id: 199, title: 'برف انبار', state_id: 4},
    {id: 176, title: 'بهاران شهر', state_id: 4},
    {id: 196, title: 'بهارستان', state_id: 4},
    {id: 166, title: 'بویین ومیاندشت', state_id: 4},
    {id: 134, title: 'پیربکران', state_id: 4},
    {id: 178, title: 'تودشک', state_id: 4},
    {id: 138, title: 'تیران', state_id: 4},
    {id: 231, title: 'جندق', state_id: 4},
    {id: 229, title: 'جوزدان', state_id: 4},
    {id: 165, title: 'جوشقان قالی', state_id: 4},
    {id: 222, title: 'چادگان', state_id: 4},
    {id: 155, title: 'چرمهین', state_id: 4},
    {id: 197, title: 'چمگردان', state_id: 4},
    {id: 175, title: 'حبیب آباد', state_id: 4},
    {id: 173, title: 'حسن اباد', state_id: 4},
    {id: 204, title: 'حنا', state_id: 4},
    {id: 135, title: 'خالدآباد', state_id: 4},
    {id: 233, title: 'خمینی شهر', state_id: 4},
    {id: 186, title: 'خوانسار', state_id: 4},
    {id: 147, title: 'خور', state_id: 4},
    {id: 193, title: 'خورزوق', state_id: 4},
    {id: 181, title: 'داران', state_id: 4},
    {id: 223, title: 'دامنه', state_id: 4},
    {id: 168, title: 'درچه', state_id: 4},
    {id: 235, title: 'دستگرد', state_id: 4},
    {id: 198, title: 'دهاقان', state_id: 4},
    {id: 140, title: 'دهق', state_id: 4},
    {id: 170, title: 'دولت آباد', state_id: 4},
    {id: 190, title: 'دیزیچه', state_id: 4},
    {id: 156, title: 'رزوه', state_id: 4},
    {id: 180, title: 'رضوانشهر', state_id: 4},
    {id: 213, title: 'زازران', state_id: 4},
    {id: 192, title: 'زاینده رود', state_id: 4},
    {id: 132, title: 'زرین شهر', state_id: 4},
    {id: 141, title: 'زواره', state_id: 4},
    {id: 131, title: 'زیار', state_id: 4},
    {id: 209, title: 'زیباشهر', state_id: 4},
    {id: 136, title: 'سجزی', state_id: 4},
    {id: 174, title: 'سده لنجان', state_id: 4},
    {id: 161, title: 'سفیدشهر', state_id: 4},
    {id: 162, title: 'سمیرم', state_id: 4},
    {id: 212, title: 'سین', state_id: 4},
    {id: 217, title: 'شاپورآباد', state_id: 4},
    {id: 195, title: 'شاهین شهر', state_id: 4},
    {id: 146, title: 'شهرضا', state_id: 4},
    {id: 232, title: 'طالخونچه', state_id: 4},
    {id: 158, title: 'طرق رود', state_id: 4},
    {id: 203, title: 'عسگران', state_id: 4},
    {id: 182, title: 'علویجه', state_id: 4},
    {id: 189, title: 'فرخی', state_id: 4},
    {id: 157, title: 'فریدونشهر', state_id: 4},
    {id: 218, title: 'فلاورجان', state_id: 4},
    {id: 150, title: 'فولادشهر', state_id: 4},
    {id: 230, title: 'قمصر', state_id: 4},
    {id: 154, title: 'قهجاورستان', state_id: 4},
    {id: 194, title: 'قهدریجان', state_id: 4},
    {id: 142, title: 'کاشان', state_id: 4},
    {id: 207, title: 'کامو و چوگان', state_id: 4},
    {id: 167, title: 'کرکوند', state_id: 4},
    {id: 152, title: 'کلیشادوسودرجان', state_id: 4},
    {id: 151, title: 'کمشچه', state_id: 4},
    {id: 228, title: 'کمه', state_id: 4},
    {id: 205, title: 'کهریزسنگ', state_id: 4},
    {id: 210, title: 'کوشک', state_id: 4},
    {id: 201, title: 'کوهپایه', state_id: 4},
    {id: 172, title: 'گرگاب', state_id: 4},
    {id: 130, title: 'گزبرخوار', state_id: 4},
    {id: 202, title: 'گلپایگان', state_id: 4},
    {id: 163, title: 'گلدشت', state_id: 4},
    {id: 133, title: 'گلشن', state_id: 4},
    {id: 179, title: 'گلشهر', state_id: 4},
    {id: 137, title: 'گوگد', state_id: 4},
    {id: 153, title: 'لای بید', state_id: 4},
    {id: 214, title: 'مبارکه', state_id: 4},
    {id: 148, title: 'مجلسی', state_id: 4},
    {id: 225, title: 'محمدآباد', state_id: 4},
    {id: 184, title: 'مشکات', state_id: 4},
    {id: 188, title: 'منظریه', state_id: 4},
    {id: 206, title: 'مهاباد', state_id: 4},
    {id: 177, title: 'میمه', state_id: 4},
    {id: 211, title: 'نایین', state_id: 4},
    {id: 187, title: 'نجف آباد', state_id: 4},
    {id: 159, title: 'نصرآباد', state_id: 4},
    {id: 224, title: 'نطنز', state_id: 4},
    {id: 227, title: 'نوش آباد', state_id: 4},
    {id: 226, title: 'نیاسر', state_id: 4},
    {id: 183, title: 'نیک آباد', state_id: 4},
    {id: 149, title: 'هرند', state_id: 4},
    {id: 215, title: 'ورزنه', state_id: 4},
    {id: 216, title: 'ورنامخواست', state_id: 4},
    {id: 219, title: 'وزوان', state_id: 4},
    {id: 139, title: 'ونک', state_id: 4},
  ],
  [
    {id: 238, title: 'آسارا', state_id: 5},
    {id: 247, title: 'اشتهارد', state_id: 5},
    {id: 250, title: 'تنکمان', state_id: 5},
    {id: 237, title: 'چهارباغ', state_id: 5},
    {id: 241, title: 'شهرجدیدهشتگرد', state_id: 5},
    {id: 240, title: 'طالقان', state_id: 5},
    {id: 253, title: 'فردیس', state_id: 5},
    {id: 239, title: 'کرج', state_id: 5},
    {id: 252, title: 'کمال شهر', state_id: 5},
    {id: 248, title: 'کوهسار', state_id: 5},
    {id: 249, title: 'گرمدره', state_id: 5},
    {id: 251, title: 'گلسار', state_id: 5},
    {id: 246, title: 'ماهدشت', state_id: 5},
    {id: 242, title: 'محمدشهر', state_id: 5},
    {id: 243, title: 'مشکین دشت', state_id: 5},
    {id: 244, title: 'نظرآباد', state_id: 5},
    {id: 245, title: 'هشتگرد', state_id: 5},
  ],
  [
    {id: 254, title: 'آبدانان', state_id: 6},
    {id: 261, title: 'آسمان آباد', state_id: 6},
    {id: 268, title: 'ارکواز', state_id: 6},
    {id: 258, title: 'ایلام', state_id: 6},
    {id: 259, title: 'ایوان', state_id: 6},
    {id: 257, title: 'بدره', state_id: 6},
    {id: 265, title: 'بلاوه', state_id: 6},
    {id: 262, title: 'پهله', state_id: 6},
    {id: 270, title: 'توحید', state_id: 6},
    {id: 273, title: 'چوار', state_id: 6},
    {id: 267, title: 'دره شهر', state_id: 6},
    {id: 278, title: 'دلگشا', state_id: 6},
    {id: 271, title: 'دهلران', state_id: 6},
    {id: 274, title: 'زرنه', state_id: 6},
    {id: 264, title: 'سراب باغ', state_id: 6},
    {id: 276, title: 'سرابله', state_id: 6},
    {id: 255, title: 'شباب', state_id: 6},
    {id: 275, title: 'صالح آباد', state_id: 6},
    {id: 272, title: 'لومار', state_id: 6},
    {id: 277, title: 'ماژین', state_id: 6},
    {id: 263, title: 'مهر', state_id: 6},
    {id: 260, title: 'مهران', state_id: 6},
    {id: 269, title: 'مورموری', state_id: 6},
    {id: 256, title: 'موسیان', state_id: 6},
    {id: 266, title: 'میمه', state_id: 6},
  ],
  [
    {id: 314, title: 'آب پخش', state_id: 7},
    {id: 296, title: 'آباد', state_id: 7},
    {id: 297, title: 'آبدان', state_id: 7},
    {id: 309, title: 'امام حسن', state_id: 7},
    {id: 301, title: 'انارستان', state_id: 7},
    {id: 282, title: 'اهرم', state_id: 7},
    {id: 306, title: 'بادوله', state_id: 7},
    {id: 280, title: 'برازجان', state_id: 7},
    {id: 313, title: 'بردخون', state_id: 7},
    {id: 305, title: 'بردستان', state_id: 7},
    {id: 291, title: 'بندردیر', state_id: 7},
    {id: 287, title: 'بندردیلم', state_id: 7},
    {id: 281, title: 'بندرریگ', state_id: 7},
    {id: 311, title: 'بندرکنگان', state_id: 7},
    {id: 295, title: 'بندرگناوه', state_id: 7},
    {id: 289, title: 'بنک', state_id: 7},
    {id: 300, title: 'بوشکان', state_id: 7},
    {id: 312, title: 'بوشهر', state_id: 7},
    {id: 308, title: 'تنگ ارم', state_id: 7},
    {id: 293, title: 'جم', state_id: 7},
    {id: 290, title: 'چغادک', state_id: 7},
    {id: 298, title: 'خارک', state_id: 7},
    {id: 284, title: 'خورموج', state_id: 7},
    {id: 294, title: 'دالکی', state_id: 7},
    {id: 304, title: 'دلوار', state_id: 7},
    {id: 283, title: 'دوراهک', state_id: 7},
    {id: 279, title: 'ریز', state_id: 7},
    {id: 310, title: 'سعد آباد', state_id: 7},
    {id: 303, title: 'سیراف', state_id: 7},
    {id: 302, title: 'شبانکاره', state_id: 7},
    {id: 299, title: 'شنبه', state_id: 7},
    {id: 307, title: 'عسلویه', state_id: 7},
    {id: 292, title: 'کاکی', state_id: 7},
    {id: 286, title: 'کلمه', state_id: 7},
    {id: 285, title: 'نخل تقی', state_id: 7},
    {id: 288, title: 'وحدتیه', state_id: 7},
  ],
  [
    {id: 348, title: 'آبسرد', state_id: 8},
    {id: 338, title: 'آبعلی', state_id: 8},
    {id: 329, title: 'احمد آباد مستوفی', state_id: 8},
    {id: 318, title: 'ارجمند', state_id: 8},
    {id: 356, title: 'اسلامشهر', state_id: 8},
    {id: 322, title: 'اندیشه', state_id: 8},
    {id: 349, title: 'باغستان', state_id: 8},
    {id: 328, title: 'باقرشهر', state_id: 8},
    {id: 341, title: 'بومهن', state_id: 8},
    {id: 327, title: 'پاکدشت', state_id: 8},
    {id: 358, title: 'پردیس', state_id: 8},
    {id: 337, title: 'پرند', state_id: 8},
    {id: 316, title: 'پیشوا', state_id: 8},
    {id: 353, title: 'تجریش', state_id: 8},
    {id: 340, title: 'تهران', state_id: 8},
    {id: 317, title: 'جوادآباد', state_id: 8},
    {id: 339, title: 'چهاردانگه', state_id: 8},
    {id: 355, title: 'حسن آباد', state_id: 8},
    {id: 357, title: 'دماوند', state_id: 8},
    {id: 347, title: 'رباطکریم', state_id: 8},
    {id: 321, title: 'رودهن', state_id: 8},
    {id: 319, title: 'ری', state_id: 8},
    {id: 315, title: 'شاهدشهر', state_id: 8},
    {id: 354, title: 'شریف آباد', state_id: 8},
    {id: 326, title: 'شمشک', state_id: 8},
    {id: 351, title: 'شهریار', state_id: 8},
    {id: 350, title: 'صالحیه', state_id: 8},
    {id: 324, title: 'صباشهر', state_id: 8},
    {id: 343, title: 'صفادشت', state_id: 8},
    {id: 332, title: 'فردوسیه', state_id: 8},
    {id: 345, title: 'فرون اباد', state_id: 8},
    {id: 336, title: 'فشم', state_id: 8},
    {id: 335, title: 'فیروزکوه', state_id: 8},
    {id: 352, title: 'قدس', state_id: 8},
    {id: 331, title: 'قرچک', state_id: 8},
    {id: 346, title: 'کهریزک', state_id: 8},
    {id: 330, title: 'کیلان', state_id: 8},
    {id: 333, title: 'گلستان', state_id: 8},
    {id: 344, title: 'لواسان', state_id: 8},
    {id: 325, title: 'ملارد', state_id: 8},
    {id: 323, title: 'نسیم شهر', state_id: 8},
    {id: 320, title: 'نصیرشهر', state_id: 8},
    {id: 342, title: 'وحیدیه', state_id: 8},
    {id: 334, title: 'ورامین', state_id: 8},
  ],
  [
    {id: 389, title: 'آلونی', state_id: 9},
    {id: 396, title: 'اردل', state_id: 9},
    {id: 375, title: 'باباحیدر', state_id: 9},
    {id: 378, title: 'بازفت', state_id: 9},
    {id: 366, title: 'بروجن', state_id: 9},
    {id: 388, title: 'بلداجی', state_id: 9},
    {id: 383, title: 'بن', state_id: 9},
    {id: 367, title: 'پردنجان', state_id: 9},
    {id: 391, title: 'جونقان', state_id: 9},
    {id: 394, title: 'چلگرد', state_id: 9},
    {id: 382, title: 'چلیچه', state_id: 9},
    {id: 376, title: 'دستنا', state_id: 9},
    {id: 387, title: 'دشتک', state_id: 9},
    {id: 368, title: 'سامان', state_id: 9},
    {id: 363, title: 'سرخون', state_id: 9},
    {id: 380, title: 'سردشت', state_id: 9},
    {id: 397, title: 'سفیددشت', state_id: 9},
    {id: 377, title: 'سودجان', state_id: 9},
    {id: 362, title: 'سورشجان', state_id: 9},
    {id: 385, title: 'شلمزار', state_id: 9},
    {id: 364, title: 'شهرکرد', state_id: 9},
    {id: 370, title: 'صمصامی', state_id: 9},
    {id: 371, title: 'طاقانک', state_id: 9},
    {id: 384, title: 'فارسان', state_id: 9},
    {id: 381, title: 'فرادبنه', state_id: 9},
    {id: 369, title: 'فرخ شهر', state_id: 9},
    {id: 372, title: 'کاج', state_id: 9},
    {id: 395, title: 'کیان', state_id: 9},
    {id: 390, title: 'گندمان', state_id: 9},
    {id: 361, title: 'گهرو', state_id: 9},
    {id: 360, title: 'گوجان', state_id: 9},
    {id: 374, title: 'لردگان', state_id: 9},
    {id: 398, title: 'مال خلیفه', state_id: 9},
    {id: 365, title: 'منج', state_id: 9},
    {id: 392, title: 'ناغان', state_id: 9},
    {id: 386, title: 'نافچ', state_id: 9},
    {id: 373, title: 'نقنه', state_id: 9},
    {id: 393, title: 'هارونی', state_id: 9},
    {id: 379, title: 'هفشجان', state_id: 9},
    {id: 359, title: 'وردنجان', state_id: 9},
  ],
  [
    {id: 417, title: 'آرین شهر', state_id: 10},
    {id: 405, title: 'آیسک', state_id: 10},
    {id: 404, title: 'ارسک', state_id: 10},
    {id: 425, title: 'اسدیه', state_id: 10},
    {id: 413, title: 'اسفدن', state_id: 10},
    {id: 399, title: 'اسلامیه', state_id: 10},
    {id: 421, title: 'بشرویه', state_id: 10},
    {id: 410, title: 'بیرجند', state_id: 10},
    {id: 415, title: 'حاجی آباد', state_id: 10},
    {id: 423, title: 'خضری دشت بیاض', state_id: 10},
    {id: 419, title: 'خوسف', state_id: 10},
    {id: 407, title: 'دیهوک', state_id: 10},
    {id: 426, title: 'زهان', state_id: 10},
    {id: 422, title: 'سرایان', state_id: 10},
    {id: 408, title: 'سربیشه', state_id: 10},
    {id: 416, title: 'سه قلعه', state_id: 10},
    {id: 400, title: 'شوسف', state_id: 10},
    {id: 424, title: 'طبس', state_id: 10},
    {id: 403, title: 'طبس مسینا', state_id: 10},
    {id: 402, title: 'عشق آباد', state_id: 10},
    {id: 411, title: 'فردوس', state_id: 10},
    {id: 401, title: 'قاین', state_id: 10},
    {id: 420, title: 'قهستان', state_id: 10},
    {id: 414, title: 'گزیک', state_id: 10},
    {id: 409, title: 'محمدشهر', state_id: 10},
    {id: 418, title: 'مود', state_id: 10},
    {id: 412, title: 'نهبندان', state_id: 10},
    {id: 406, title: 'نیمبلوک', state_id: 10},
  ],
  [
    {id: 472, title: 'احمدابادصولت', state_id: 11},
    {id: 489, title: 'انابد', state_id: 11},
    {id: 438, title: 'باجگیران', state_id: 11},
    {id: 476, title: 'باخرز', state_id: 11},
    {id: 427, title: 'بار', state_id: 11},
    {id: 491, title: 'بایک', state_id: 11},
    {id: 439, title: 'بجستان', state_id: 11},
    {id: 445, title: 'بردسکن', state_id: 11},
    {id: 478, title: 'بیدخت', state_id: 11},
    {id: 479, title: 'تایباد', state_id: 11},
    {id: 488, title: 'تربت جام', state_id: 11},
    {id: 475, title: 'تربت حیدریه', state_id: 11},
    {id: 464, title: 'جغتای', state_id: 11},
    {id: 429, title: 'جنگل', state_id: 11},
    {id: 456, title: 'چاپشلو', state_id: 11},
    {id: 443, title: 'چکنه', state_id: 11},
    {id: 440, title: 'چناران', state_id: 11},
    {id: 487, title: 'خرو', state_id: 11},
    {id: 498, title: 'خلیل آباد', state_id: 11},
    {id: 496, title: 'خواف', state_id: 11},
    {id: 460, title: 'داورزن', state_id: 11},
    {id: 441, title: 'درگز', state_id: 11},
    {id: 430, title: 'درود', state_id: 11},
    {id: 492, title: 'دولت آباد', state_id: 11},
    {id: 431, title: 'رباط سنگ', state_id: 11},
    {id: 457, title: 'رشتخوار', state_id: 11},
    {id: 474, title: 'رضویه', state_id: 11},
    {id: 497, title: 'روداب', state_id: 11},
    {id: 494, title: 'ریوش', state_id: 11},
    {id: 482, title: 'سبزوار', state_id: 11},
    {id: 493, title: 'سرخس', state_id: 11},
    {id: 477, title: 'سفیدسنگ', state_id: 11},
    {id: 437, title: 'سلامی', state_id: 11},
    {id: 432, title: 'سلطان آباد', state_id: 11},
    {id: 468, title: 'سنگان', state_id: 11},
    {id: 454, title: 'شادمهر', state_id: 11},
    {id: 451, title: 'شاندیز', state_id: 11},
    {id: 453, title: 'ششتمد', state_id: 11},
    {id: 473, title: 'شهراباد', state_id: 11},
    {id: 486, title: 'شهرزو', state_id: 11},
    {id: 459, title: 'صالح آباد', state_id: 11},
    {id: 495, title: 'طرقبه', state_id: 11},
    {id: 455, title: 'عشق آباد', state_id: 11},
    {id: 461, title: 'فرهادگرد', state_id: 11},
    {id: 433, title: 'فریمان', state_id: 11},
    {id: 480, title: 'فیروزه', state_id: 11},
    {id: 483, title: 'فیض آباد', state_id: 11},
    {id: 481, title: 'قاسم آباد', state_id: 11},
    {id: 458, title: 'قدمگاه', state_id: 11},
    {id: 449, title: 'قلندرآباد', state_id: 11},
    {id: 466, title: 'قوچان', state_id: 11},
    {id: 462, title: 'کاخک', state_id: 11},
    {id: 435, title: 'کاریز', state_id: 11},
    {id: 450, title: 'کاشمر', state_id: 11},
    {id: 447, title: 'کدکن', state_id: 11},
    {id: 442, title: 'کلات', state_id: 11},
    {id: 470, title: 'کندر', state_id: 11},
    {id: 484, title: 'گلمکان', state_id: 11},
    {id: 434, title: 'گناباد', state_id: 11},
    {id: 485, title: 'لطف آباد', state_id: 11},
    {id: 465, title: 'مزدآوند', state_id: 11},
    {id: 446, title: 'مشهد', state_id: 11},
    {id: 463, title: 'مشهدریزه', state_id: 11},
    {id: 490, title: 'ملک آباد', state_id: 11},
    {id: 452, title: 'نشتیفان', state_id: 11},
    {id: 444, title: 'نصرآباد', state_id: 11},
    {id: 448, title: 'نقاب', state_id: 11},
    {id: 469, title: 'نوخندان', state_id: 11},
    {id: 471, title: 'نیشابور', state_id: 11},
    {id: 428, title: 'نیل شهر', state_id: 11},
    {id: 436, title: 'همت آباد', state_id: 11},
    {id: 467, title: 'یونسی', state_id: 11},
  ],
  [
    {id: 509, title: 'آشخانه', state_id: 12},
    {id: 514, title: 'آوا', state_id: 12},
    {id: 504, title: 'اسفراین', state_id: 12},
    {id: 518, title: 'ایور', state_id: 12},
    {id: 512, title: 'بجنورد', state_id: 12},
    {id: 501, title: 'پیش قلعه', state_id: 12},
    {id: 510, title: 'تیتکانلو', state_id: 12},
    {id: 511, title: 'جاجرم', state_id: 12},
    {id: 499, title: 'چناران شهر', state_id: 12},
    {id: 508, title: 'حصارگرمخان', state_id: 12},
    {id: 513, title: 'درق', state_id: 12},
    {id: 500, title: 'راز', state_id: 12},
    {id: 515, title: 'زیارت', state_id: 12},
    {id: 516, title: 'سنخواست', state_id: 12},
    {id: 503, title: 'شوقان', state_id: 12},
    {id: 507, title: 'شیروان', state_id: 12},
    {id: 517, title: 'صفی آباد', state_id: 12},
    {id: 519, title: 'فاروج', state_id: 12},
    {id: 506, title: 'قاضی', state_id: 12},
    {id: 502, title: 'قوشخانه', state_id: 12},
    {id: 505, title: 'گرمه', state_id: 12},
    {id: 520, title: 'لوجلی', state_id: 12},
  ],
  [
    {id: 586, title: 'آبادان', state_id: 13},
    {id: 538, title: 'آبژدان', state_id: 13},
    {id: 582, title: 'آزادی', state_id: 13},
    {id: 577, title: 'آغاجاری', state_id: 13},
    {id: 576, title: 'ابوحمیظه', state_id: 13},
    {id: 556, title: 'اروندکنار', state_id: 13},
    {id: 595, title: 'الهایی', state_id: 13},
    {id: 553, title: 'الوان', state_id: 13},
    {id: 592, title: 'امیدیه', state_id: 13},
    {id: 552, title: 'اندیمشک', state_id: 13},
    {id: 565, title: 'اهواز', state_id: 13},
    {id: 578, title: 'ایذه', state_id: 13},
    {id: 596, title: 'باغ ملک', state_id: 13},
    {id: 563, title: 'بستان', state_id: 13},
    {id: 530, title: 'بندرامام خمینی', state_id: 13},
    {id: 561, title: 'بندرماهشهر', state_id: 13},
    {id: 574, title: 'بهبهان', state_id: 13},
    {id: 522, title: 'بیدروبه', state_id: 13},
    {id: 542, title: 'ترکالکی', state_id: 13},
    {id: 558, title: 'تشان', state_id: 13},
    {id: 562, title: 'جایزان', state_id: 13},
    {id: 585, title: 'جنت مکان', state_id: 13},
    {id: 533, title: 'چغامیش', state_id: 13},
    {id: 535, title: 'چم گلک', state_id: 13},
    {id: 591, title: 'چمران', state_id: 13},
    {id: 539, title: 'چویبده', state_id: 13},
    {id: 536, title: 'حر', state_id: 13},
    {id: 569, title: 'حسینیه', state_id: 13},
    {id: 524, title: 'حمزه', state_id: 13},
    {id: 547, title: 'حمیدیه', state_id: 13},
    {id: 588, title: 'خرمشهر', state_id: 13},
    {id: 590, title: 'خنافره', state_id: 13},
    {id: 543, title: 'دارخوین', state_id: 13},
    {id: 584, title: 'دزفول', state_id: 13},
    {id: 548, title: 'دهدز', state_id: 13},
    {id: 559, title: 'رامشیر', state_id: 13},
    {id: 529, title: 'رامهرمز', state_id: 13},
    {id: 551, title: 'رفیع', state_id: 13},
    {id: 528, title: 'زهره', state_id: 13},
    {id: 554, title: 'سالند', state_id: 13},
    {id: 557, title: 'سرداران', state_id: 13},
    {id: 544, title: 'سردشت', state_id: 13},
    {id: 572, title: 'سماله', state_id: 13},
    {id: 593, title: 'سوسنگرد', state_id: 13},
    {id: 580, title: 'سیاه منصور', state_id: 13},
    {id: 560, title: 'شادگان', state_id: 13},
    {id: 523, title: 'شاوور', state_id: 13},
    {id: 526, title: 'شرافت', state_id: 13},
    {id: 537, title: 'شمس آباد', state_id: 13},
    {id: 567, title: 'شهر امام', state_id: 13},
    {id: 583, title: 'شوش', state_id: 13},
    {id: 573, title: 'شوشتر', state_id: 13},
    {id: 594, title: 'شیبان', state_id: 13},
    {id: 555, title: 'صالح شهر', state_id: 13},
    {id: 597, title: 'صفی آباد', state_id: 13},
    {id: 579, title: 'صیدون', state_id: 13},
    {id: 566, title: 'فتح المبین', state_id: 13},
    {id: 549, title: 'قلعه تل', state_id: 13},
    {id: 568, title: 'قلعه خواجه', state_id: 13},
    {id: 546, title: 'کوت سیدنعیم', state_id: 13},
    {id: 531, title: 'کوت عبداله', state_id: 13},
    {id: 525, title: 'گتوند', state_id: 13},
    {id: 570, title: 'گلگیر', state_id: 13},
    {id: 587, title: 'گوریه', state_id: 13},
    {id: 545, title: 'لالی', state_id: 13},
    {id: 540, title: 'مسجدسلیمان', state_id: 13},
    {id: 589, title: 'مشراگه', state_id: 13},
    {id: 541, title: 'مقاومت', state_id: 13},
    {id: 534, title: 'ملاثانی', state_id: 13},
    {id: 527, title: 'منصوریه', state_id: 13},
    {id: 550, title: 'میانرود', state_id: 13},
    {id: 532, title: 'میداود', state_id: 13},
    {id: 571, title: 'مینوشهر', state_id: 13},
    {id: 521, title: 'هفتگل', state_id: 13},
    {id: 575, title: 'هندیجان', state_id: 13},
    {id: 581, title: 'هویزه', state_id: 13},
    {id: 564, title: 'ویس', state_id: 13},
  ],
  [
    {id: 600, title: 'آب بر', state_id: 14},
    {id: 608, title: 'ابهر', state_id: 14},
    {id: 601, title: 'ارمغانخانه', state_id: 14},
    {id: 613, title: 'چورزق', state_id: 14},
    {id: 610, title: 'حلب', state_id: 14},
    {id: 605, title: 'خرمدره', state_id: 14},
    {id: 609, title: 'دندی', state_id: 14},
    {id: 618, title: 'زرین آباد', state_id: 14},
    {id: 599, title: 'زرین رود', state_id: 14},
    {id: 614, title: 'زنجان', state_id: 14},
    {id: 598, title: 'سجاس', state_id: 14},
    {id: 604, title: 'سلطانیه', state_id: 14},
    {id: 615, title: 'سهرورد', state_id: 14},
    {id: 616, title: 'صایین قلعه', state_id: 14},
    {id: 607, title: 'قیدار', state_id: 14},
    {id: 602, title: 'کرسف', state_id: 14},
    {id: 612, title: 'گرماب', state_id: 14},
    {id: 617, title: 'ماه نشان', state_id: 14},
    {id: 611, title: 'نوربهار', state_id: 14},
    {id: 606, title: 'نیک پی', state_id: 14},
    {id: 603, title: 'هیدج', state_id: 14},
  ],
  [
    {id: 638, title: 'آرادان', state_id: 15},
    {id: 633, title: 'امیریه', state_id: 15},
    {id: 619, title: 'ایوانکی', state_id: 15},
    {id: 632, title: 'بسطام', state_id: 15},
    {id: 636, title: 'بیارجمند', state_id: 15},
    {id: 621, title: 'دامغان', state_id: 15},
    {id: 630, title: 'درجزین', state_id: 15},
    {id: 629, title: 'دیباج', state_id: 15},
    {id: 631, title: 'رودیان', state_id: 15},
    {id: 622, title: 'سرخه', state_id: 15},
    {id: 625, title: 'سمنان', state_id: 15},
    {id: 624, title: 'شاهرود', state_id: 15},
    {id: 635, title: 'شهمیرزاد', state_id: 15},
    {id: 637, title: 'کلاته', state_id: 15},
    {id: 628, title: 'کلاته خیج', state_id: 15},
    {id: 626, title: 'کهن آباد', state_id: 15},
    {id: 627, title: 'گرمسار', state_id: 15},
    {id: 620, title: 'مجن', state_id: 15},
    {id: 623, title: 'مهدی شهر', state_id: 15},
    {id: 634, title: 'میامی', state_id: 15},
  ],
  [
    {id: 663, title: 'ادیمی', state_id: 16},
    {id: 660, title: 'اسپکه', state_id: 16},
    {id: 666, title: 'ایرانشهر', state_id: 16},
    {id: 659, title: 'بزمان', state_id: 16},
    {id: 651, title: 'بمپور', state_id: 16},
    {id: 645, title: 'بنت', state_id: 16},
    {id: 641, title: 'بنجار', state_id: 16},
    {id: 652, title: 'پیشین', state_id: 16},
    {id: 647, title: 'جالق', state_id: 16},
    {id: 657, title: 'چاه بهار', state_id: 16},
    {id: 672, title: 'خاش', state_id: 16},
    {id: 665, title: 'دوست محمد', state_id: 16},
    {id: 644, title: 'راسک', state_id: 16},
    {id: 664, title: 'زابل', state_id: 16},
    {id: 656, title: 'زابلی', state_id: 16},
    {id: 655, title: 'زاهدان', state_id: 16},
    {id: 658, title: 'زرآباد', state_id: 16},
    {id: 650, title: 'زهک', state_id: 16},
    {id: 662, title: 'سراوان', state_id: 16},
    {id: 667, title: 'سرباز', state_id: 16},
    {id: 671, title: 'سوران', state_id: 16},
    {id: 668, title: 'سیرکان', state_id: 16},
    {id: 640, title: 'شهرک علی اکبر', state_id: 16},
    {id: 661, title: 'فنوج', state_id: 16},
    {id: 646, title: 'قصرقند', state_id: 16},
    {id: 673, title: 'کنارک', state_id: 16},
    {id: 653, title: 'گشت', state_id: 16},
    {id: 642, title: 'گلمورتی', state_id: 16},
    {id: 654, title: 'محمدآباد', state_id: 16},
    {id: 674, title: 'محمدان', state_id: 16},
    {id: 639, title: 'محمدی', state_id: 16},
    {id: 669, title: 'میرجاوه', state_id: 16},
    {id: 670, title: 'نصرت آباد', state_id: 16},
    {id: 643, title: 'نگور', state_id: 16},
    {id: 649, title: 'نوک آباد', state_id: 16},
    {id: 675, title: 'نیک شهر', state_id: 16},
    {id: 648, title: 'هیدوچ', state_id: 16},
  ],
  [
    {id: 776, title: 'آباده', state_id: 17},
    {id: 719, title: 'آباده طشک', state_id: 17},
    {id: 736, title: 'اردکان', state_id: 17},
    {id: 687, title: 'ارسنجان', state_id: 17},
    {id: 709, title: 'استهبان', state_id: 17},
    {id: 774, title: 'اسیر', state_id: 17},
    {id: 715, title: 'اشکنان', state_id: 17},
    {id: 722, title: 'افزر', state_id: 17},
    {id: 767, title: 'اقلید', state_id: 17},
    {id: 699, title: 'امام شهر', state_id: 17},
    {id: 755, title: 'اهل', state_id: 17},
    {id: 694, title: 'اوز', state_id: 17},
    {id: 750, title: 'ایج', state_id: 17},
    {id: 692, title: 'ایزدخواست', state_id: 17},
    {id: 683, title: 'باب انار', state_id: 17},
    {id: 701, title: 'بابامنیر', state_id: 17},
    {id: 760, title: 'بالاده', state_id: 17},
    {id: 729, title: 'بنارویه', state_id: 17},
    {id: 754, title: 'بهمن', state_id: 17},
    {id: 710, title: 'بوانات', state_id: 17},
    {id: 689, title: 'بیرم', state_id: 17},
    {id: 696, title: 'بیضا', state_id: 17},
    {id: 758, title: 'جنت شهر', state_id: 17},
    {id: 700, title: 'جهرم', state_id: 17},
    {id: 734, title: 'جویم', state_id: 17},
    {id: 744, title: 'حاجی آباد', state_id: 17},
    {id: 733, title: 'حسامی', state_id: 17},
    {id: 705, title: 'حسن اباد', state_id: 17},
    {id: 708, title: 'خانه زنیان', state_id: 17},
    {id: 763, title: 'خانیمن', state_id: 17},
    {id: 745, title: 'خاوران', state_id: 17},
    {id: 720, title: 'خرامه', state_id: 17},
    {id: 756, title: 'خشت', state_id: 17},
    {id: 707, title: 'خنج', state_id: 17},
    {id: 751, title: 'خور', state_id: 17},
    {id: 735, title: 'خوزی', state_id: 17},
    {id: 679, title: 'خومه زار', state_id: 17},
    {id: 740, title: 'داراب', state_id: 17},
    {id: 770, title: 'داریان', state_id: 17},
    {id: 682, title: 'دبیران', state_id: 17},
    {id: 688, title: 'دژکرد', state_id: 17},
    {id: 690, title: 'دهرم', state_id: 17},
    {id: 718, title: 'دوبرجی', state_id: 17},
    {id: 723, title: 'دوزه', state_id: 17},
    {id: 684, title: 'رامجرد', state_id: 17},
    {id: 771, title: 'رونیز', state_id: 17},
    {id: 726, title: 'زاهدشهر', state_id: 17},
    {id: 713, title: 'زرقان', state_id: 17},
    {id: 728, title: 'سده', state_id: 17},
    {id: 685, title: 'سروستان', state_id: 17},
    {id: 730, title: 'سعادت شهر', state_id: 17},
    {id: 680, title: 'سلطان شهر', state_id: 17},
    {id: 732, title: 'سورمق', state_id: 17},
    {id: 724, title: 'سیدان', state_id: 17},
    {id: 748, title: 'ششده', state_id: 17},
    {id: 704, title: 'شهرپیر', state_id: 17},
    {id: 731, title: 'شهرصدرا', state_id: 17},
    {id: 691, title: 'شیراز', state_id: 17},
    {id: 714, title: 'صغاد', state_id: 17},
    {id: 766, title: 'صفاشهر', state_id: 17},
    {id: 693, title: 'علامرودشت', state_id: 17},
    {id: 768, title: 'عمادده', state_id: 17},
    {id: 678, title: 'فدامی', state_id: 17},
    {id: 712, title: 'فراشبند', state_id: 17},
    {id: 703, title: 'فسا', state_id: 17},
    {id: 681, title: 'فیروزآباد', state_id: 17},
    {id: 727, title: 'قادراباد', state_id: 17},
    {id: 716, title: 'قایمیه', state_id: 17},
    {id: 686, title: 'قره بلاغ', state_id: 17},
    {id: 762, title: 'قطب آباد', state_id: 17},
    {id: 737, title: 'قطرویه', state_id: 17},
    {id: 761, title: 'قیر', state_id: 17},
    {id: 677, title: 'کارزین (فتح آباد)', state_id: 17},
    {id: 676, title: 'کازرون', state_id: 17},
    {id: 706, title: 'کامفیروز', state_id: 17},
    {id: 772, title: 'کره ای', state_id: 17},
    {id: 698, title: 'کنارتخته', state_id: 17},
    {id: 742, title: 'کوار', state_id: 17},
    {id: 725, title: 'کوپن', state_id: 17},
    {id: 747, title: 'کوهنجان', state_id: 17},
    {id: 702, title: 'گراش', state_id: 17},
    {id: 717, title: 'گله دار', state_id: 17},
    {id: 773, title: 'لار', state_id: 17},
    {id: 777, title: 'لامرد', state_id: 17},
    {id: 753, title: 'لپویی', state_id: 17},
    {id: 711, title: 'لطیفی', state_id: 17},
    {id: 769, title: 'مادرسلیمان', state_id: 17},
    {id: 739, title: 'مبارک آباددیز', state_id: 17},
    {id: 746, title: 'مرودشت', state_id: 17},
    {id: 749, title: 'مزایجان', state_id: 17},
    {id: 759, title: 'مشکان', state_id: 17},
    {id: 764, title: 'مصیری', state_id: 17},
    {id: 757, title: 'مهر', state_id: 17},
    {id: 765, title: 'میانشهر', state_id: 17},
    {id: 721, title: 'میمند', state_id: 17},
    {id: 743, title: 'نوبندگان', state_id: 17},
    {id: 752, title: 'نوجین', state_id: 17},
    {id: 738, title: 'نودان', state_id: 17},
    {id: 741, title: 'نورآباد', state_id: 17},
    {id: 697, title: 'نی ریز', state_id: 17},
    {id: 775, title: 'هماشهر', state_id: 17},
    {id: 695, title: 'وراوی', state_id: 17},
  ],
  [
    {id: 783, title: 'آبگرم', state_id: 18},
    {id: 800, title: 'آبیک', state_id: 18},
    {id: 798, title: 'آوج', state_id: 18},
    {id: 788, title: 'ارداق', state_id: 18},
    {id: 797, title: 'اسفرورین', state_id: 18},
    {id: 786, title: 'اقبالیه', state_id: 18},
    {id: 789, title: 'الوند', state_id: 18},
    {id: 793, title: 'بویین زهرا', state_id: 18},
    {id: 779, title: 'بیدستان', state_id: 18},
    {id: 802, title: 'تاکستان', state_id: 18},
    {id: 790, title: 'خاکعلی', state_id: 18},
    {id: 782, title: 'خرمدشت', state_id: 18},
    {id: 799, title: 'دانسفهان', state_id: 18},
    {id: 781, title: 'رازمیان', state_id: 18},
    {id: 778, title: 'سگزآباد', state_id: 18},
    {id: 791, title: 'سیردان', state_id: 18},
    {id: 784, title: 'شال', state_id: 18},
    {id: 785, title: 'شریفیه', state_id: 18},
    {id: 792, title: 'ضیاڈآباد', state_id: 18},
    {id: 801, title: 'قزوین', state_id: 18},
    {id: 780, title: 'کوهین', state_id: 18},
    {id: 794, title: 'محمدیه', state_id: 18},
    {id: 795, title: 'محمودآبادنمونه', state_id: 18},
    {id: 796, title: 'معلم کلایه', state_id: 18},
    {id: 787, title: 'نرجه', state_id: 18},
  ],
  [
    {id: 806, title: 'جعفریه', state_id: 19},
    {id: 808, title: 'دستجرد', state_id: 19},
    {id: 805, title: 'سلفچگان', state_id: 19},
    {id: 804, title: 'قم', state_id: 19},
    {id: 807, title: 'قنوات', state_id: 19},
    {id: 803, title: 'کهک', state_id: 19},
  ],
  [
    {id: 836, title: 'آرمرده', state_id: 20},
    {id: 828, title: 'اورامان تخت', state_id: 20},
    {id: 823, title: 'بابارشانی', state_id: 20},
    {id: 818, title: 'بانه', state_id: 20},
    {id: 825, title: 'برده رشه', state_id: 20},
    {id: 833, title: 'بلبان آباد', state_id: 20},
    {id: 812, title: 'بویین سفلی', state_id: 20},
    {id: 827, title: 'بیجار', state_id: 20},
    {id: 834, title: 'پیرتاج', state_id: 20},
    {id: 810, title: 'توپ آغاج', state_id: 20},
    {id: 837, title: 'چناره', state_id: 20},
    {id: 831, title: 'دزج', state_id: 20},
    {id: 814, title: 'دلبران', state_id: 20},
    {id: 822, title: 'دهگلان', state_id: 20},
    {id: 824, title: 'دیواندره', state_id: 20},
    {id: 813, title: 'زرینه', state_id: 20},
    {id: 811, title: 'سروآباد', state_id: 20},
    {id: 820, title: 'سریش آباد', state_id: 20},
    {id: 832, title: 'سقز', state_id: 20},
    {id: 815, title: 'سنندج', state_id: 20},
    {id: 826, title: 'شویشه', state_id: 20},
    {id: 821, title: 'صاحب', state_id: 20},
    {id: 809, title: 'قروه', state_id: 20},
    {id: 835, title: 'کامیاران', state_id: 20},
    {id: 830, title: 'کانی دینار', state_id: 20},
    {id: 829, title: 'کانی سور', state_id: 20},
    {id: 819, title: 'مریوان', state_id: 20},
    {id: 817, title: 'موچش', state_id: 20},
    {id: 816, title: 'یاسوکند', state_id: 20},
  ],
  [
    {id: 870, title: 'اختیارآباد', state_id: 21},
    {id: 905, title: 'ارزوییه', state_id: 21},
    {id: 865, title: 'امین شهر', state_id: 21},
    {id: 908, title: 'انار', state_id: 21},
    {id: 862, title: 'اندوهجرد', state_id: 21},
    {id: 886, title: 'باغین', state_id: 21},
    {id: 859, title: 'بافت', state_id: 21},
    {id: 866, title: 'بردسیر', state_id: 21},
    {id: 871, title: 'بروات', state_id: 21},
    {id: 887, title: 'بزنجان', state_id: 21},
    {id: 880, title: 'بلورد', state_id: 21},
    {id: 839, title: 'بلوک', state_id: 21},
    {id: 843, title: 'بم', state_id: 21},
    {id: 879, title: 'بهرمان', state_id: 21},
    {id: 840, title: 'پاریز', state_id: 21},
    {id: 855, title: 'جبالبارز', state_id: 21},
    {id: 846, title: 'جوپار', state_id: 21},
    {id: 848, title: 'جوزم', state_id: 21},
    {id: 883, title: 'جیرفت', state_id: 21},
    {id: 854, title: 'چترود', state_id: 21},
    {id: 892, title: 'خاتون اباد', state_id: 21},
    {id: 844, title: 'خانوک', state_id: 21},
    {id: 896, title: 'خواجو شهر', state_id: 21},
    {id: 864, title: 'خورسند', state_id: 21},
    {id: 899, title: 'درب بهشت', state_id: 21},
    {id: 894, title: 'دشتکار', state_id: 21},
    {id: 876, title: 'دهج', state_id: 21},
    {id: 875, title: 'دوساری', state_id: 21},
    {id: 897, title: 'رابر', state_id: 21},
    {id: 891, title: 'راور', state_id: 21},
    {id: 898, title: 'راین', state_id: 21},
    {id: 867, title: 'رفسنجان', state_id: 21},
    {id: 857, title: 'رودبار', state_id: 21},
    {id: 872, title: 'ریحان', state_id: 21},
    {id: 888, title: 'زرند', state_id: 21},
    {id: 842, title: 'زنگی آباد', state_id: 21},
    {id: 901, title: 'زهکلوت', state_id: 21},
    {id: 852, title: 'زیدآباد', state_id: 21},
    {id: 856, title: 'سیرجان', state_id: 21},
    {id: 904, title: 'شهداد', state_id: 21},
    {id: 907, title: 'شهربابک', state_id: 21},
    {id: 860, title: 'صفاییه', state_id: 21},
    {id: 847, title: 'عنبرآباد', state_id: 21},
    {id: 877, title: 'فاریاب', state_id: 21},
    {id: 881, title: 'فهرج', state_id: 21},
    {id: 885, title: 'قلعه گنج', state_id: 21},
    {id: 882, title: 'کاظم آباد', state_id: 21},
    {id: 858, title: 'کرمان', state_id: 21},
    {id: 851, title: 'کشکوییه', state_id: 21},
    {id: 838, title: 'کهنوج', state_id: 21},
    {id: 873, title: 'کوهبنان', state_id: 21},
    {id: 845, title: 'کیانشهر', state_id: 21},
    {id: 890, title: 'گلباف', state_id: 21},
    {id: 878, title: 'گلزار', state_id: 21},
    {id: 841, title: 'گنبکی', state_id: 21},
    {id: 850, title: 'لاله زار', state_id: 21},
    {id: 874, title: 'ماهان', state_id: 21},
    {id: 869, title: 'محمدآباد', state_id: 21},
    {id: 902, title: 'محی آباد', state_id: 21},
    {id: 903, title: 'مردهک', state_id: 21},
    {id: 895, title: 'مس سرچشمه', state_id: 21},
    {id: 861, title: 'منوجان', state_id: 21},
    {id: 884, title: 'نجف شهر', state_id: 21},
    {id: 893, title: 'نرماشیر', state_id: 21},
    {id: 849, title: 'نظام شهر', state_id: 21},
    {id: 906, title: 'نگار', state_id: 21},
    {id: 889, title: 'نودژ', state_id: 21},
    {id: 863, title: 'هجدک', state_id: 21},
    {id: 868, title: 'هماشهر', state_id: 21},
    {id: 853, title: 'هنزا', state_id: 21},
    {id: 900, title: 'یزدان شهر', state_id: 21},
  ],
  [
    {id: 925, title: 'ازگله', state_id: 22},
    {id: 933, title: 'اسلام آبادغرب', state_id: 22},
    {id: 911, title: 'بانوره', state_id: 22},
    {id: 931, title: 'باینگان', state_id: 22},
    {id: 919, title: 'بیستون', state_id: 22},
    {id: 924, title: 'پاوه', state_id: 22},
    {id: 912, title: 'تازه آباد', state_id: 22},
    {id: 914, title: 'جوانرود', state_id: 22},
    {id: 920, title: 'حمیل', state_id: 22},
    {id: 938, title: 'رباط', state_id: 22},
    {id: 923, title: 'روانسر', state_id: 22},
    {id: 930, title: 'ریجاب', state_id: 22},
    {id: 929, title: 'سرپل ذهاب', state_id: 22},
    {id: 934, title: 'سرمست', state_id: 22},
    {id: 922, title: 'سطر', state_id: 22},
    {id: 909, title: 'سنقر', state_id: 22},
    {id: 935, title: 'سومار', state_id: 22},
    {id: 910, title: 'شاهو', state_id: 22},
    {id: 939, title: 'صحنه', state_id: 22},
    {id: 915, title: 'قصرشیرین', state_id: 22},
    {id: 926, title: 'کرمانشاه', state_id: 22},
    {id: 917, title: 'کرند', state_id: 22},
    {id: 928, title: 'کنگاور', state_id: 22},
    {id: 918, title: 'کوزران', state_id: 22},
    {id: 937, title: 'گهواره', state_id: 22},
    {id: 940, title: 'گودین', state_id: 22},
    {id: 921, title: 'گیلانغرب', state_id: 22},
    {id: 927, title: 'میان راهان', state_id: 22},
    {id: 936, title: 'نودشه', state_id: 22},
    {id: 916, title: 'نوسود', state_id: 22},
    {id: 932, title: 'هرسین', state_id: 22},
    {id: 913, title: 'هلشی', state_id: 22},
  ],
  [
    {id: 952, title: 'باشت', state_id: 23},
    {id: 953, title: 'پاتاوه', state_id: 23},
    {id: 956, title: 'چرام', state_id: 23},
    {id: 948, title: 'چیتاب', state_id: 23},
    {id: 944, title: 'دهدشت', state_id: 23},
    {id: 947, title: 'دوگنبدان', state_id: 23},
    {id: 950, title: 'دیشموک', state_id: 23},
    {id: 946, title: 'سرفاریاب', state_id: 23},
    {id: 957, title: 'سوق', state_id: 23},
    {id: 943, title: 'سی سخت', state_id: 23},
    {id: 954, title: 'قلعه رییسی', state_id: 23},
    {id: 941, title: 'گراب سفلی', state_id: 23},
    {id: 942, title: 'لنده', state_id: 23},
    {id: 949, title: 'لیکک', state_id: 23},
    {id: 951, title: 'مادوان', state_id: 23},
    {id: 955, title: 'مارگون', state_id: 23},
    {id: 945, title: 'یاسوج', state_id: 23},
  ],
  [
    {id: 984, title: 'آزادشهر', state_id: 24},
    {id: 967, title: 'آق قلا', state_id: 24},
    {id: 985, title: 'انبارآلوم', state_id: 24},
    {id: 980, title: 'اینچه برون', state_id: 24},
    {id: 965, title: 'بندرترکمن', state_id: 24},
    {id: 972, title: 'بندرگز', state_id: 24},
    {id: 982, title: 'تاتارعلیا', state_id: 24},
    {id: 986, title: 'جلین', state_id: 24},
    {id: 978, title: 'خان ببین', state_id: 24},
    {id: 971, title: 'دلند', state_id: 24},
    {id: 960, title: 'رامیان', state_id: 24},
    {id: 968, title: 'سرخنکلاته', state_id: 24},
    {id: 970, title: 'سنگدوین', state_id: 24},
    {id: 958, title: 'سیمین شهر', state_id: 24},
    {id: 977, title: 'علی اباد', state_id: 24},
    {id: 981, title: 'فاضل آباد', state_id: 24},
    {id: 961, title: 'فراغی', state_id: 24},
    {id: 963, title: 'کردکوی', state_id: 24},
    {id: 979, title: 'کلاله', state_id: 24},
    {id: 969, title: 'گالیکش', state_id: 24},
    {id: 975, title: 'گرگان', state_id: 24},
    {id: 976, title: 'گمیش تپه', state_id: 24},
    {id: 962, title: 'گنبدکاووس', state_id: 24},
    {id: 964, title: 'مراوه', state_id: 24},
    {id: 959, title: 'مزرعه', state_id: 24},
    {id: 974, title: 'مینودشت', state_id: 24},
    {id: 966, title: 'نگین شهر', state_id: 24},
    {id: 973, title: 'نوده خاندوز', state_id: 24},
    {id: 983, title: 'نوکنده', state_id: 24},
  ],
  [
    {id: 1028, title: 'آستارا', state_id: 25},
    {id: 1037, title: 'آستانه اشرفیه', state_id: 25},
    {id: 997, title: 'احمدسرگوراب', state_id: 25},
    {id: 1013, title: 'اسالم', state_id: 25},
    {id: 999, title: 'اطاقور', state_id: 25},
    {id: 1006, title: 'املش', state_id: 25},
    {id: 1003, title: 'بازار جمعه', state_id: 25},
    {id: 1027, title: 'بره سر', state_id: 25},
    {id: 1005, title: 'بندرانزلی', state_id: 25},
    {id: 1026, title: 'پره سر', state_id: 25},
    {id: 1009, title: 'توتکابن', state_id: 25},
    {id: 1030, title: 'جیرنده', state_id: 25},
    {id: 1036, title: 'چابکسر', state_id: 25},
    {id: 1031, title: 'چاف و چمخاله', state_id: 25},
    {id: 1002, title: 'چوبر', state_id: 25},
    {id: 1034, title: 'حویق', state_id: 25},
    {id: 989, title: 'خشکبیجار', state_id: 25},
    {id: 1022, title: 'خمام', state_id: 25},
    {id: 1014, title: 'دیلمان', state_id: 25},
    {id: 1038, title: 'رانکوه', state_id: 25},
    {id: 995, title: 'رحیم آباد', state_id: 25},
    {id: 1007, title: 'رستم آباد', state_id: 25},
    {id: 1020, title: 'رشت', state_id: 25},
    {id: 994, title: 'رضوانشهر', state_id: 25},
    {id: 1018, title: 'رودبار', state_id: 25},
    {id: 1029, title: 'رودبنه', state_id: 25},
    {id: 1015, title: 'رودسر', state_id: 25},
    {id: 991, title: 'سنگر', state_id: 25},
    {id: 1035, title: 'سیاهکل', state_id: 25},
    {id: 1017, title: 'شفت', state_id: 25},
    {id: 988, title: 'شلمان', state_id: 25},
    {id: 1012, title: 'صومعه سرا', state_id: 25},
    {id: 1001, title: 'فومن', state_id: 25},
    {id: 1004, title: 'کلاچای', state_id: 25},
    {id: 1011, title: 'کوچصفهان', state_id: 25},
    {id: 1019, title: 'کومله', state_id: 25},
    {id: 1016, title: 'کیاشهر', state_id: 25},
    {id: 1033, title: 'گوراب زرمیخ', state_id: 25},
    {id: 1008, title: 'لاهیجان', state_id: 25},
    {id: 1000, title: 'لشت نشاء', state_id: 25},
    {id: 1010, title: 'لنگرود', state_id: 25},
    {id: 998, title: 'لوشان', state_id: 25},
    {id: 1032, title: 'لولمان', state_id: 25},
    {id: 996, title: 'لوندویل', state_id: 25},
    {id: 993, title: 'لیسار', state_id: 25},
    {id: 1023, title: 'ماسال', state_id: 25},
    {id: 1021, title: 'ماسوله', state_id: 25},
    {id: 990, title: 'ماکلوان', state_id: 25},
    {id: 992, title: 'مرجقل', state_id: 25},
    {id: 987, title: 'منجیل', state_id: 25},
    {id: 1025, title: 'هشتپر (تالش)', state_id: 25},
    {id: 1024, title: 'واجارگاه', state_id: 25},
  ],
  [
    {id: 1058, title: 'ازنا', state_id: 26},
    {id: 1061, title: 'اشترینان', state_id: 26},
    {id: 1047, title: 'الشتر', state_id: 26},
    {id: 1052, title: 'الیگودرز', state_id: 26},
    {id: 1046, title: 'بروجرد', state_id: 26},
    {id: 1040, title: 'بیران شهر', state_id: 26},
    {id: 1043, title: 'پلدختر', state_id: 26},
    {id: 1039, title: 'چالانچولان', state_id: 26},
    {id: 1051, title: 'چقابل', state_id: 26},
    {id: 1060, title: 'خرم آباد', state_id: 26},
    {id: 1063, title: 'درب گنبد', state_id: 26},
    {id: 1049, title: 'دورود', state_id: 26},
    {id: 1050, title: 'زاغه', state_id: 26},
    {id: 1056, title: 'سپیددشت', state_id: 26},
    {id: 1057, title: 'سراب دوره', state_id: 26},
    {id: 1042, title: 'شول آباد', state_id: 26},
    {id: 1062, title: 'فیروزآباد', state_id: 26},
    {id: 1044, title: 'کوهدشت', state_id: 26},
    {id: 1054, title: 'کوهنانی', state_id: 26},
    {id: 1059, title: 'گراب', state_id: 26},
    {id: 1053, title: 'معمولان', state_id: 26},
    {id: 1048, title: 'مومن آباد', state_id: 26},
    {id: 1055, title: 'نورآباد', state_id: 26},
    {id: 1045, title: 'هفت چشمه', state_id: 26},
    {id: 1041, title: 'ویسیان', state_id: 26},
  ],
  [
    {id: 1100, title: 'آلاشت', state_id: 27},
    {id: 1101, title: 'آمل', state_id: 27},
    {id: 1075, title: 'ارطه', state_id: 27},
    {id: 1089, title: 'امامزاده عبدالله', state_id: 27},
    {id: 1076, title: 'امیرکلا', state_id: 27},
    {id: 1072, title: 'ایزدشهر', state_id: 27},
    {id: 1098, title: 'بابل', state_id: 27},
    {id: 1104, title: 'بابلسر', state_id: 27},
    {id: 1097, title: 'بلده', state_id: 27},
    {id: 1095, title: 'بهشهر', state_id: 27},
    {id: 1069, title: 'بهنمیر', state_id: 27},
    {id: 1078, title: 'پایین هولار', state_id: 27},
    {id: 1065, title: 'پل سفید', state_id: 27},
    {id: 1094, title: 'پول', state_id: 27},
    {id: 1070, title: 'تنکابن', state_id: 27},
    {id: 1099, title: 'جویبار', state_id: 27},
    {id: 1067, title: 'چالوس', state_id: 27},
    {id: 1120, title: 'چمستان', state_id: 27},
    {id: 1116, title: 'خرم آباد', state_id: 27},
    {id: 1083, title: 'خلیل شهر', state_id: 27},
    {id: 1111, title: 'خوش رودپی', state_id: 27},
    {id: 1066, title: 'دابودشت', state_id: 27},
    {id: 1081, title: 'رامسر', state_id: 27},
    {id: 1118, title: 'رستمکلا', state_id: 27},
    {id: 1107, title: 'رویان', state_id: 27},
    {id: 1114, title: 'رینه', state_id: 27},
    {id: 1108, title: 'زرگرمحله', state_id: 27},
    {id: 1088, title: 'زیرآب', state_id: 27},
    {id: 1113, title: 'ساری', state_id: 27},
    {id: 1115, title: 'سرخرود', state_id: 27},
    {id: 1074, title: 'سلمان شهر', state_id: 27},
    {id: 1119, title: 'سورک', state_id: 27},
    {id: 1106, title: 'شیرگاه', state_id: 27},
    {id: 1105, title: 'شیرود', state_id: 27},
    {id: 1109, title: 'عباس اباد', state_id: 27},
    {id: 1087, title: 'فریدونکنار', state_id: 27},
    {id: 1091, title: 'فریم', state_id: 27},
    {id: 1110, title: 'قایم شهر', state_id: 27},
    {id: 1103, title: 'کتالم وسادات شهر', state_id: 27},
    {id: 1117, title: 'کجور', state_id: 27},
    {id: 1096, title: 'کلارآباد', state_id: 27},
    {id: 1071, title: 'کلاردشت', state_id: 27},
    {id: 1077, title: 'کوهی خیل', state_id: 27},
    {id: 1068, title: 'کیاسر', state_id: 27},
    {id: 1084, title: 'کیاکلا', state_id: 27},
    {id: 1073, title: 'گتاب', state_id: 27},
    {id: 1079, title: 'گزنک', state_id: 27},
    {id: 1064, title: 'گلوگاه', state_id: 27},
    {id: 1080, title: 'محمودآباد', state_id: 27},
    {id: 1112, title: 'مرزن آباد', state_id: 27},
    {id: 1086, title: 'مرزیکلا', state_id: 27},
    {id: 1093, title: 'نشتارود', state_id: 27},
    {id: 1102, title: 'نکا', state_id: 27},
    {id: 1085, title: 'نور', state_id: 27},
    {id: 1082, title: 'نوشهر', state_id: 27},
    {id: 1092, title: 'هادی شهر', state_id: 27},
    {id: 1090, title: 'هچیرود', state_id: 27},
  ],
  [
    {id: 1121, title: 'آستانه', state_id: 28},
    {id: 1125, title: 'آشتیان', state_id: 28},
    {id: 1148, title: 'آوه', state_id: 28},
    {id: 1139, title: 'اراک', state_id: 28},
    {id: 1144, title: 'پرندک', state_id: 28},
    {id: 1137, title: 'تفرش', state_id: 28},
    {id: 1140, title: 'توره', state_id: 28},
    {id: 1149, title: 'جاورسیان', state_id: 28},
    {id: 1131, title: 'خشکرود', state_id: 28},
    {id: 1150, title: 'خمین', state_id: 28},
    {id: 1122, title: 'خنجین', state_id: 28},
    {id: 1129, title: 'خنداب', state_id: 28},
    {id: 1152, title: 'داودآباد', state_id: 28},
    {id: 1143, title: 'دلیجان', state_id: 28},
    {id: 1126, title: 'رازقان', state_id: 28},
    {id: 1138, title: 'زاویه', state_id: 28},
    {id: 1132, title: 'ساروق', state_id: 28},
    {id: 1135, title: 'ساوه', state_id: 28},
    {id: 1134, title: 'شازند', state_id: 28},
    {id: 1153, title: 'شهباز', state_id: 28},
    {id: 1128, title: 'غرق آباد', state_id: 28},
    {id: 1142, title: 'فرمهین', state_id: 28},
    {id: 1130, title: 'قورچی باشی', state_id: 28},
    {id: 1145, title: 'کارچان', state_id: 28},
    {id: 1124, title: 'کمیجان', state_id: 28},
    {id: 1151, title: 'مامونیه', state_id: 28},
    {id: 1133, title: 'محلات', state_id: 28},
    {id: 1127, title: 'مهاجران', state_id: 28},
    {id: 1136, title: 'میلاجرد', state_id: 28},
    {id: 1123, title: 'نراق', state_id: 28},
    {id: 1141, title: 'نوبران', state_id: 28},
    {id: 1146, title: 'نیمور', state_id: 28},
    {id: 1147, title: 'هندودر', state_id: 28},
  ],
  [
    {id: 1169, title: 'ابوموسی', state_id: 29},
    {id: 1190, title: 'بستک', state_id: 29},
    {id: 1185, title: 'بندرجاسک', state_id: 29},
    {id: 1161, title: 'بندرعباس', state_id: 29},
    {id: 1189, title: 'بندرلنگه', state_id: 29},
    {id: 1154, title: 'بیکاء', state_id: 29},
    {id: 1173, title: 'پارسیان', state_id: 29},
    {id: 1176, title: 'تازیان پایین', state_id: 29},
    {id: 1191, title: 'تخت', state_id: 29},
    {id: 1155, title: 'تیرور', state_id: 29},
    {id: 1175, title: 'جناح', state_id: 29},
    {id: 1182, title: 'چارک', state_id: 29},
    {id: 1183, title: 'حاجی اباد', state_id: 29},
    {id: 1181, title: 'خمیر', state_id: 29},
    {id: 1172, title: 'درگهان', state_id: 29},
    {id: 1188, title: 'دشتی', state_id: 29},
    {id: 1177, title: 'دهبارز', state_id: 29},
    {id: 1166, title: 'رویدر', state_id: 29},
    {id: 1162, title: 'زیارتعلی', state_id: 29},
    {id: 1171, title: 'سردشت', state_id: 29},
    {id: 1160, title: 'سرگز', state_id: 29},
    {id: 1163, title: 'سندرک', state_id: 29},
    {id: 1180, title: 'سوزا', state_id: 29},
    {id: 1179, title: 'سیریک', state_id: 29},
    {id: 1168, title: 'فارغان', state_id: 29},
    {id: 1184, title: 'فین', state_id: 29},
    {id: 1157, title: 'قشم', state_id: 29},
    {id: 1167, title: 'قلعه قاضی', state_id: 29},
    {id: 1174, title: 'کنگ', state_id: 29},
    {id: 1158, title: 'کوشکنار', state_id: 29},
    {id: 1164, title: 'کوهستک', state_id: 29},
    {id: 1159, title: 'کیش', state_id: 29},
    {id: 1156, title: 'گروک', state_id: 29},
    {id: 1186, title: 'گوهران', state_id: 29},
    {id: 1165, title: 'لمزان', state_id: 29},
    {id: 1178, title: 'میناب', state_id: 29},
    {id: 1187, title: 'هرمز', state_id: 29},
    {id: 1170, title: 'هشتبندی', state_id: 29},
  ],
  [
    {id: 1195, title: 'آجین', state_id: 30},
    {id: 1206, title: 'ازندریان', state_id: 30},
    {id: 1213, title: 'اسدآباد', state_id: 30},
    {id: 1197, title: 'برزول', state_id: 30},
    {id: 1200, title: 'بهار', state_id: 30},
    {id: 1212, title: 'تویسرکان', state_id: 30},
    {id: 1196, title: 'جورقان', state_id: 30},
    {id: 1217, title: 'جوکار', state_id: 30},
    {id: 1193, title: 'دمق', state_id: 30},
    {id: 1216, title: 'رزن', state_id: 30},
    {id: 1192, title: 'زنگنه', state_id: 30},
    {id: 1199, title: 'سامن', state_id: 30},
    {id: 1194, title: 'سرکان', state_id: 30},
    {id: 1202, title: 'شیرین سو', state_id: 30},
    {id: 1211, title: 'صالح آباد', state_id: 30},
    {id: 1198, title: 'فامنین', state_id: 30},
    {id: 1201, title: 'فرسفج', state_id: 30},
    {id: 1204, title: 'فیروزان', state_id: 30},
    {id: 1205, title: 'قروه درجزین', state_id: 30},
    {id: 1220, title: 'قهاوند', state_id: 30},
    {id: 1219, title: 'کبودرآهنگ', state_id: 30},
    {id: 1208, title: 'گل تپه', state_id: 30},
    {id: 1209, title: 'گیان', state_id: 30},
    {id: 1207, title: 'لالجین', state_id: 30},
    {id: 1203, title: 'مریانج', state_id: 30},
    {id: 1210, title: 'ملایر', state_id: 30},
    {id: 1218, title: 'مهاجران', state_id: 30},
    {id: 1215, title: 'نهاوند', state_id: 30},
    {id: 1214, title: 'همدان', state_id: 30},
  ],
  [
    {id: 1230, title: 'ابرکوه', state_id: 31},
    {id: 1241, title: 'احمدآباد', state_id: 31},
    {id: 1233, title: 'اردکان', state_id: 31},
    {id: 1225, title: 'اشکذر', state_id: 31},
    {id: 1237, title: 'بافق', state_id: 31},
    {id: 1235, title: 'بفروییه', state_id: 31},
    {id: 1229, title: 'بهاباد', state_id: 31},
    {id: 1224, title: 'تفت', state_id: 31},
    {id: 1223, title: 'حمیدیا', state_id: 31},
    {id: 1238, title: 'خضرآباد', state_id: 31},
    {id: 1231, title: 'زارچ', state_id: 31},
    {id: 1236, title: 'شاهدیه', state_id: 31},
    {id: 1228, title: 'عقدا', state_id: 31},
    {id: 1221, title: 'مروست', state_id: 31},
    {id: 1222, title: 'مهردشت', state_id: 31},
    {id: 1240, title: 'مهریز', state_id: 31},
    {id: 1239, title: 'میبد', state_id: 31},
    {id: 1226, title: 'ندوشن', state_id: 31},
    {id: 1232, title: 'نیر', state_id: 31},
    {id: 1234, title: 'هرات', state_id: 31},
    {id: 1227, title: 'یزد', state_id: 31},
  ],
];

export const provinces = [
  {
    id: 1,
    title: 'آذربایجان شرقی',
  },
  {
    id: 2,
    title: 'آذربایجان غربی',
  },
  {
    id: 3,
    title: 'اردبیل',
  },
  {
    id: 4,
    title: 'اصفهان',
  },
  {
    id: 5,
    title: 'البرز',
  },
  {
    id: 6,
    title: 'ایلام',
  },
  {
    id: 7,
    title: 'بوشهر',
  },
  {
    id: 8,
    title: 'تهران',
  },
  {
    id: 9,
    title: 'چهارمحال و بختیاری',
  },
  {
    id: 10,
    title: 'خراسان جنوبی',
  },
  {
    id: 11,
    title: 'خراسان رضوی',
  },
  {
    id: 12,
    title: 'خراسان شمالی',
  },
  {
    id: 13,
    title: 'خوزستان',
  },
  {
    id: 14,
    title: 'زنجان',
  },
  {
    id: 15,
    title: 'سمنان',
  },
  {
    id: 16,
    title: 'سیستان و بلوچستان',
  },
  {
    id: 17,
    title: 'فارس',
  },
  {
    id: 18,
    title: 'قزوین',
  },
  {
    id: 19,
    title: 'قم',
  },
  {
    id: 20,
    title: 'كردستان',
  },
  {
    id: 21,
    title: 'كرمان',
  },
  {
    id: 22,
    title: 'كرمانشاه',
  },
  {
    id: 23,
    title: 'کهگیلویه و بویراحمد',
  },
  {
    id: 24,
    title: 'گلستان',
  },
  {
    id: 25,
    title: 'گیلان',
  },
  {
    id: 26,
    title: 'لرستان',
  },
  {
    id: 27,
    title: 'مازندران',
  },
  {
    id: 28,
    title: 'مركزی',
  },
  {
    id: 29,
    title: 'هرمزگان',
  },
  {
    id: 30,
    title: 'همدان',
  },
  {
    id: 31,
    title: 'یزد',
  },
];
export const subject = [
  {id: 1, title: ' پیشنهاد'},
  {id: 2, title: ' انتقاد و شکایت'},
  {id: 3, title: ' پیگیری سفارش'},
];
